BASE_URL="https://api.themoviedb.org/3/"
IMAGE_URL="https://image.tmdb.org/t/p/w780"
DISCOVER_MOVIE_URL="discover/movie?api_key=328c283cd27bd1877d9080ccb1604c91"
MOVIE_DETAILS_URL="movie/{movie_id}?api_key=328c283cd27bd1877d9080ccb1604c91"
